# Generated by Django 5.1 on 2024-08-26 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('loanPayments', 'Loan Payments'), ('bankFees', 'Bank Fees'), ('entertainment', 'Entertainment'), ('foodAndDrink', 'Food And Drink'), ('generalMerchandise', 'General Merchandise'), ('homeImprovement', 'Home Improvement'), ('medical', 'Medical'), ('personalCare', 'Personal Care'), ('generalServices', 'General Services'), ('governmentAndNonProfit', 'Government And Non Profit'), ('transportation', 'Transportation'), ('travel', 'Travel'), ('rentAndUtilities', 'Rent And Utilities')], max_length=31)),
                ('subcategory', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
