name: Blog API CI

on:
  push:
    branches: [main]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Set Up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: 3.12.2

  #     - name: Create Virtual Environment
  #       run: |
  #         python -m venv venv
  #         source venv/bin/activate

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install -U pip
  #         python -m pip install -r requirements.txt

  #     - name: Print debugging information
  #       run: |
  #         echo "Python Version: $(python --version)"
  #         echo "Working Directory: $(pwd)"
  #         echo "Contents of Working Directory: $(ls -l)"
  #         echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

  test:
    runs-on: ubuntu-latest

    env:
      CI_MODE: 1
      SECRET_KEY: Gate Gate Paragate Parasamgate Bodhi Svaha

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Run databse migrations
        run: python manage.py migrate

      - name: Run the tests
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Do Deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"